site_name: C4D Guide
site_description: A simple multilingual documentation site
site_author: Your Name
site_url: https://lasr21.github.io/c4d_guide/

# Repository
repo_name: lasr21/c4d_guide
repo_url: https://github.com/lasr21/c4d_guide

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: es

# Plugins
plugins:
  - search:
      lang: 
        - es
        - en
        - pt
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: es
          default: true
          name: Español
          build: true
        - locale: en
          name: English
          build: true
        - locale: pt
          name: Português
          build: true

# Navigation
nav:
  - Inicio: index.md

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

# Extra
extra:
  alternate:
    - name: Español
      link: ./es/
      lang: es
    - name: English
      link: ./en/
      lang: en
    - name: Português
      link: ./pt/
      lang: pt
